import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import SessionWrapper from "../providers/SessionWrapper";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Prodify",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <SessionWrapper>
        <header className="sticky top-0 z-999 backdrop-blur-3xl">
         <Navbar/>
       </header>
        <div className="min-h-screen max-w-7xl px-4 md:px-10 xl:px-0 mx-auto py-10 md:pb-16 lg:pb-20 ">
          {children}
        </div>
        <Footer/>
       </SessionWrapper>
        <Toaster position="top-right" reverseOrder={false} />
      </body>
    </html>
  );
}
